import type {NextPage} from "next";
import {signIn, signOut, useSession} from "next-auth/react";
import Head from "next/head";
import {useEffect} from "react";
import {FaDiscord, FaLeaf} from "react-icons/fa";

const Home: NextPage = () => {
  const { data } = useSession();

  useEffect(() => {
    console.log(data )
  }, [data]);


  if (!data)
    return (
      <div className="min-h-screen flex grow flex-col items-center justify-center">
        <div className="text-2xl font-bold">Please log in below</div>
        <div className="p-4" />
        <button
          onClick={() => signIn("discord")}
          className="flex items-center gap-2 rounded bg-gray-200 px-4 py-2 text-2xl text-black"
        >
          <span>Sign in with Discord</span>
          <FaDiscord />
        </button>
      </div>
    );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="w-full absolute p-4">
        <button
          onClick={() => signOut()}
          className="ml-auto flex items-center gap-2 rounded bg-gray-200 px-4 py-2 text-2xl text-black"
        >
          <span>Sign out</span>
          <FaLeaf/>
        </button>
      </nav>
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Create <span className="text-purple-300">T3</span> App
        </h1>
        <p className="text-2xl text-gray-700">This stack uses:</p>
        <div className="mx-auto p-10 bg-black text-white">
          <div className="flex animate-fade-in-delay justify-center p-8">
            <FaDiscord/>
          </div>
        </div>
      </main>
    </>
  );
};



export default Home;
